parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        bind:
            $debug: '%kernel.debug%'
            $defaultLocale: '%nfq_seo.default_locale%'
            $locales: '%locales%'

    Nfq\SeoBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Exception,Model,Tests,Utils,NfqSeoBundle.php}'

    Nfq\SeoBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Nfq\SeoBundle\EventListener\SeoInvalidateSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Nfq\SeoBundle\Routing\SeoRouter:
        decorates: 'router.default'
        arguments:
            $router: '@Nfq\SeoBundle\Routing\SeoRouter.inner'
